openapi: 3.0.0
info:
  title: Menahub Api
  version: 1.0.0

servers:
  - url: http://localhost:3002

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ValidationError:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: Validation failed
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          example:
            name: ["Name is required"]
            email: ["Invalid email"]
            password: ["Password must be at least 6 characters"]

    ConflictError:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: User already exists

paths:
  /api/V1/auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  minLength: 1
                  description: Full name of the user
                email:
                  type: string
                  format: email
                  description: Valid email address
                password:
                  type: string
                  minLength: 6
                  description: Minimum 6 characters
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '409':
          description: Conflict (e.g., user already exists)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictError'

  /api/V1/auth/login:
    post:
      tags:
        - Auth
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 6
      responses:
        '200':
          description: Login successful
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
